apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-benchmark
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-benchmark
  template:
    metadata:
      labels:
        app: llm-benchmark
    spec:
      containers:
      - name: llm-benchmark
        image: vitorfs/llm-benchmark:latest
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama:11434"
---
apiVersion: v1
kind: Service
metadata:
  name: llm-benchmark
  namespace: apps
spec:
  selector:
    app: llm-benchmark
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-benchmark
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: benchmark.unbund.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: llm-benchmark
            port:
              number: 80
