apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: networking
type: Opaque
stringData:
    token: eyJhIjoiZmNhZGZiNzE1NjljYWZjOTM0MDkxMzlmN2UxNmJlODgiLCJ0IjoiMjIwNTFlNDMtYmM4NC00MzhkLWI3YzMtYjgyOWMxZTJmNmFkIiwicyI6IlptWmhObVkyTjJZdE5ESmhOeTAwT1RFekxUazBaVFl0Tm1KbU9EbGtOR0V3WmpGaCJ9
