apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://8gears.github.io/n8n-helm-chart/
    chart: n8n
    targetRevision: 0.23.x
    helm:
      values: |
        config:
          host: n8n.unbund.com
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: n8n.unbund.com
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          enabled: false # Per your previous request to avoid PVCs where possible
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
