apiVersion: ENC[AES256_GCM,data:cUs=,iv:cajrsyDohY4xgLPbZDGLzuqSg1xTNOskCYUP4dzs5sg=,tag:b2ssNro4UJ9SGSi7UmhZ0g==,type:str]
kind: ENC[AES256_GCM,data:EkgLgXtm,iv:xWXbmRIXSAt04OqUp5rCdKh7le5fRpKA/a1zzFo3zvQ=,tag:VHbIZ6wrX8EZmPnnoqDmRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vsZb+bdTneHMj+Xuq2Gszm/kcyjLVLg=,iv:ps6/SdVJXvvv9/MsVZjf0rkkJTYqHnuDFN5Q029viOc=,tag:3J8wVXkbBdFspn7uuis2bA==,type:str]
    namespace: ENC[AES256_GCM,data:2A4SyVhproLNmA==,iv:kgz9+RbEG+4OFSwYtKCse703E6Qh64NUAdMcXMvYEjU=,tag:d2C7bM2eN0ZzW+O/tsYvKw==,type:str]
type: ENC[AES256_GCM,data:8aIg0W9G,iv:6xTfOaX7/QsmyvlFHcKM/srkyAxJzYU9HhPf8axJeuc=,tag:/NAuP4YbiHM3gk73mvkn3g==,type:str]
stringData:
    token: ENC[AES256_GCM,data:s+A+FJIKeantyWZfNw2LkvDc+r9g9D7qgswFVbKDwfhC2hatSbhprLRbJ9RrAUawESbWvlh98na2l95SUq6OCKgQRTcLv7YMoFd1EwvxkJJS6XE5Mqk3bMNBouwiHO0xi8dj8sMpYVFIOkHXsQtZJj7EiIkIjDiHftLsHUCQYr6A+f6hKOnCc8t0iMG/za8Orfwe60IERij2GayxkjReEQnqBJ+0IWe96BflvmI5nFuT4jqsB7r8VA==,iv:tp0u8FGMLrl/qccx+mUo3WZXgy3uv/qZrFhx//gdfoE=,tag:nYKkokX5D7j55T5RURbipQ==,type:str]
sops:
    age:
        - recipient: age13569lxaxj29guql3ue2gqs2jyz8upa6mp5xcz3g49tlfte6k8slqrgvykp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcjhCMmF3WGtYb2xuOWZG
            NTNWZXE3eTBvZ09LUHVPeWc0SzFQdHN6S0JnClcxeFZQZmpLWVd3SHU0b2I2MVpu
            SlQ0N2tMTC9lWnVPNXl2Q25pK2ZwblkKLS0tIDY1NWF1M2t1Uy83YzVjTGNxTDh0
            RmVFak1Qb3UydGZnWnllYVZuSWwxN2MKKUGA0O7XTMLzCNHLoJUi44syRwHY3tB7
            0g24BAomtOkwWV9xIXU+Z+oJkdeTC3Rar4I31D5V6qCe2rqVI5qixw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:37:23Z"
    mac: ENC[AES256_GCM,data:SHz21/cKDafdZ/EVtBxq6B0/UC7V23dKtYEVD+CAeY2KlewHDtZeI/6gE9Z1DKyfMqr9k+PYz9LruiT9uDY7S6kurAe2p35pUXGiOnO0SJJtdp/+ipdSKGJfQsz9SWM5hkwxr3Hfd+2oX2lotN8PzmFYnmeNmMJaAAzEoewr7Qs=,iv:3FUwVB6Pl499mLKGrkkwpWUBcr6H+13zwZ5MpWmmrS0=,tag:O1b2BUgb/sDWb0+VXzpmSQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
