apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-model-puller
  namespace: ollama
spec:
  template:
    spec:
      containers:
      - name: puller
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            MODELS="llama3.2 deepseek-coder-v2:lite phi3 gemma2:9b qwen2.5:7b minimax-m2.5:cloud"
            for model in $MODELS; do
              echo "Pulling $model..."
              curl -X POST http://ollama.ollama.svc.cluster.local:11434/api/pull -d "{"name": "$model"}"
            done
      restartPolicy: OnFailure
  backoffLimit: 4
