apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langflow
  template:
    metadata:
      labels:
        app: langflow
    spec:
      containers:
      - name: langflow
        image: logspace/langflow:1.1.2
        ports:
        - containerPort: 7860
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: LANGFLOW_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: langflow
  namespace: apps
spec:
  selector:
    app: langflow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7860
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langflow
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: agents.unbund.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: langflow
            port:
              number: 80
