apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: networking
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2024.2.1
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: cloudflare-api-token
          items:
          - key: api-token
            path: credentials.json
      - name: config
        configMap:
          name: cloudflared-config
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: networking
data:
  config.yaml: |
    tunnel: 22051e43-bc84-438d-b7c3-b829c1e2f6ad
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: chat.unbund.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: agents.unbund.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: benchmark.unbund.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: n8n.unbund.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: claw.unbund.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: grafana.unbund.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: homer.unbund.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404
