apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-webui.github.io/helm-charts
    chart: open-webui
    targetRevision: 4.x.x
    helm:
      values: |
        ollama:
          enabled: false
        ollamaUrls:
          - http://ollama:11434
        ingress:
          enabled: true
          className: nginx
          host: chat.unbund.com
        persistence:
          enabled: true
          size: 5Gi
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
